server:
  port: 8080
  servlet:
    context-path: /house/backend

spring:
  datasource:
    url: jdbc:mysql://121.42.145.216:3306/house_service?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: house_service
    password: house_pwd_2021$
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
mybatis:
  mapper-locations: classpath:mapper/**/*.xml,classpath*:mapper/*.xml,classpath*:mapper/base/*/*.xml,classpath*:mapper/extend/*/*.xml,classpath*:mapping/*.xml,classpath*:mapper/extend/*.xml,classpath*:mapper/base/*.xml
  type-handlers-package: com.house.backend.pojo

app:
  apiWhiteName: queryUserInfoPage, hello