package com.house.backend.houseservice.dto.sys;

import com.house.backend.houseservice.common.CommonRequest;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

@Data
public class SysUserDto extends CommonRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UID
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UNAME
     *
     * @mbg.generated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NICK
     *
     * @mbg.generated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PWD
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SALT
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.LOCK
     *
     * @mbg.generated
     */
    private Boolean lock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CREATED
     *
     * @mbg.generated
     */
    private LocalDateTime created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UPDATED
     *
     * @mbg.generated
     */
    private LocalDateTime updated;


}